# Generated by Django 5.2.1 on 2025-06-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_feliz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='subservicio',
            field=models.CharField(choices=[('revision', 'Revisión clínica'), ('aseo', 'Arreglos y aseo'), ('quirurgico', 'Intervenciones quirúrgicas')], default='revision', max_length=20),
        ),
    ]
