# Generated by Django 5.2.1 on 2025-06-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_feliz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
