# Generated by Django 5.2.1 on 2026-03-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota_feliz', '0002_normalize_cita_subservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='pagada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='subservicio',
            field=models.CharField(choices=[('revision', 'Revision clinica'), ('aseo', 'Arreglos y aseo'), ('quirurgico', 'Intervenciones quirurgicas')], default='revision', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('movil', 'Movil')], max_length=20),
        ),
        migrations.CreateModel(
            name='TransaccionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbk_token', models.CharField(max_length=100, unique=True)),
                ('url_pago', models.URLField()),
                ('estado', models.CharField(choices=[('INIT', 'Iniciada'), ('OK', 'Pagada'), ('FAIL', 'Fallida')], default='INIT', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='mascota_feliz.orden')),
            ],
        ),
    ]
